using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace UIControllerGenerator.Generator;

[Generator]
public class UIControllerGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        // 初始化
    }

    public void Execute(GeneratorExecutionContext context)
    {
        // 获取当前语法树
        var syntaxTrees = context.Compilation.SyntaxTrees;
        GenerateUIControllerExecute(context, syntaxTrees);
    }

    #region GenerateUIController

    private void GenerateUIControllerExecute(GeneratorExecutionContext context, IEnumerable<SyntaxTree> syntaxTrees)
    {
        var controllerTypes = new List<(string className, string namespaceName)>();

        foreach (var tree in syntaxTrees)
        {
            // 获取语法树的根节点
            var root = tree.GetRoot();

            // 获取当前语法树中的所有命名空间节点
            var namespaces = root.DescendantNodes().OfType<NamespaceDeclarationSyntax>();

            // 判断语法树是否在指定检测的命名空间下
            if (namespaces.All(ns => !Definition.TargetNameSpaces.Contains(ns.Name.ToString())))
            {
                continue;
            }

            var classes = GetMatchClasses(root);
            foreach (var classNode in classes)
            {
                var className = classNode.Identifier.Text;
                var namespaceName = GetNamespace(classNode);
                controllerTypes.Add((className, namespaceName));
            }
        }

        if (controllerTypes.Count > 0)
        {
            var scriptContent = GenerateUIControllerCode(controllerTypes);
            context.AddSource($"UIController_Gen.g.cs", scriptContent);
        }
    }

    private string GenerateUIControllerCode(List<(string className, string namespaceName)> controllerTypes)
    {
        var sb = new StringBuilder();

        sb.AppendLine("//----------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// \tThis code was generated by the source generator.");
        sb.AppendLine("// \tChanges to this file may cause incorrect behavior.");
        sb.AppendLine("// \twill be lost if the code is regenerated.");
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("//----------------------------------------------------------");
        sb.AppendLine();

        foreach (var usingNameSpace in Definition.UsingNameSpace)
        {
            sb.AppendLine($"using {usingNameSpace};");
        }

        sb.AppendLine();
        sb.AppendLine($"namespace {Definition.NameSpace}");
        {
            sb.AppendLine("{");
            sb.AppendLine($"\tpublic sealed partial class {Definition.TargetClassName}");
            {
                sb.AppendLine("\t{");

                // 生成字段
                sb.AppendLine("\t\t#region UIController");
                sb.AppendLine();
                sb.AppendLine("\t\tprivate List<IUIController> m_uiControllers = new List<IUIController>();");
                sb.AppendLine();

                // 生成 RegisterAllController 方法
                sb.AppendLine("\t\tpartial void RegisterAllController()");
                {
                    sb.AppendLine("\t\t{");
                    foreach (var (className, _) in controllerTypes)
                    {
                        sb.AppendLine($"\t\t\tAddUIController<{className}>();");
                    }
                    sb.AppendLine("\t\t}");
                }

                sb.AppendLine();

                // 生成 AddUIController 方法
                sb.AppendLine("\t\tprivate void AddUIController<T>() where T : IUIController, new()");
                {
                    sb.AppendLine("\t\t{");
                    sb.AppendLine("\t\t\tfor (int i = 0; i < m_uiControllers.Count; i++)");
                    {
                        sb.AppendLine("\t\t\t{");
                        sb.AppendLine("\t\t\t\tvar type = m_uiControllers[i].GetType();");
                        sb.AppendLine("\t\t\t\tif (type == typeof(T))");
                        {
                            sb.AppendLine("\t\t\t\t{");
                            sb.AppendLine("\t\t\t\t\tDLogger.Fatal(\"repeat controller type: {0}\", typeof(T).Name);");
                            sb.AppendLine("\t\t\t\t\treturn;");
                            sb.AppendLine("\t\t\t\t}");
                        }
                        sb.AppendLine("\t\t\t}");
                    }
                    sb.AppendLine();
                    sb.AppendLine("\t\t\tvar controller = new T();");
                    sb.AppendLine("\t\t\tm_uiControllers.Add(controller);");
                    sb.AppendLine();
                    sb.AppendLine("\t\t\tcontroller.RegUIMessage();");
                    sb.AppendLine("\t\t}");
                }

                sb.AppendLine();
                sb.AppendLine("\t\t#endregion");
                sb.AppendLine("\t}");
            }
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    /// <summary>
    /// 获取匹配的类声明语法（实现了 IUIController 接口的类）
    /// </summary>
    private IEnumerable<ClassDeclarationSyntax> GetMatchClasses(SyntaxNode root)
        => root.DescendantNodes().OfType<ClassDeclarationSyntax>()
            .Where(c => c.BaseList != null &&
                       c.BaseList.Types.Any(t => t.Type.ToString().Equals(Definition.InterfaceName)));

    /// <summary>
    /// 获取类所在的命名空间
    /// </summary>
    private string GetNamespace(ClassDeclarationSyntax classNode)
    {
        var namespaceNode = classNode.Ancestors().OfType<NamespaceDeclarationSyntax>().FirstOrDefault();
        return namespaceNode?.Name.ToString() ?? string.Empty;
    }

    #endregion
}
